<?php
        require("../shared/authenticationController.php");
	require("util/db.inc.php");
	require("util/functions.inc.php");
	require("util/dateFunctions.inc.php");
	require("util/numberFunctions.inc.php");
	require("util/incomingInvoiceFunctions.inc.php");
	require("util/plannedvalueFunctions.inc.php");
?>